app/routes.py
import os
import uuid
from flask import Flask, Blueprint, render_template, request, redirect, url_for, session, flash, jsonify
from flask_session import Session
from flask_wtf import FlaskForm
from wtforms import FileField, SelectField, StringField, PasswordField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length, EqualTo, NumberRange
from werkzeug.utils import secure_filename
from .models import get_user, update_user, add_user, user_exists, init_db, verify_password, add_fantasy_league, get_league_by_code, get_public_leagues, save_prediction, get_user_predictions, get_league_by_id, get_user_leagues, is_user_in_league, add_user_to_league, get_league_leaderboard, place_bet, get_profile_pic, get_db_connection, get_user_player_predictions, save_player_prediction, ensure_user_in_global_league, get_seasonal_league_leaderboard, get_recent_league_bets, process_all_bets
from .player_prediction_model import PlayerPredictionSystem
import aiohttp
from understat import Understat # https://github.com/amosbastian/understat
import json
from datetime import datetime

main = Blueprint('main', __name__)
app = Flask(__name__)

LEAGUE_MAPPING = {
    "epl": "Premier League",
    "La_liga": "La Liga",
    "Bundesliga": "Bundesliga", 
    "Serie_A": "Serie A",
    "Ligue_1": "Ligue 1"
}

LEAGUE_ICONS = {
    "epl": "PremLogo.png",
    "La_liga": "LaLigaLogo.png",
    "Bundesliga": "BundesligaLogo.png",
    "Serie_A": "SerieALogo.png", 
    "Ligue_1": "Ligue1Logo.png"
}

DEFAULT_LEAGUE = "epl"

UPLOAD_FOLDER = 'app/static/profilepics/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
os.makedirs(UPLOAD_FOLDER, exist_ok=True)


    # Initialize database before the first request
@main.before_app_request
def initialise_database():
    init_db()
    
    
@main.route('/')
async def homepage():
    for league_code in LEAGUE_MAPPING:
        league_name = LEAGUE_MAPPING[league_code]
        async with aiohttp.ClientSession() as session:
            understat = Understat(session)
            table = await understat.get_league_table(league_code, 2024, with_headers=False)
            results = await understat.get_league_results(league_code, 2024)
            recent_results = sorted(results, key=lambda x: x["datetime"], reverse=True)[:5]
            fixtures = await understat.get_league_fixtures(league_code, 2024)
            upcoming_fixtures = sorted(fixtures, key=lambda x: x["datetime"])[:5]
            return render_template("main.html",  # change it if you want. dont bother
                            league_name=league_name,
                            league_code=league_code,
                            table=table,
                            recent_results=recent_results,
                            upcoming_fixtures=upcoming_fixtures)



@main.route('/league/<league_code>')
@main.route('/league')  # Deafault to prem
async def league_view(league_code=DEFAULT_LEAGUE):
    # Just to make sure it's in mapping above
    if league_code not in LEAGUE_MAPPING:
        league_code = DEFAULT_LEAGUE
    league_name = LEAGUE_MAPPING[league_code]
    
    async with aiohttp.ClientSession() as session:
        understat = Understat(session)
        table = await understat.get_league_table(league_code, 2024, with_headers=False)
        
        results = await understat.get_league_results(league_code, 2024)
        recent_results = sorted(results, key=lambda x: x["datetime"], reverse=True)[:5]
        
        fixtures = await understat.get_league_fixtures(league_code, 2024)
        upcoming_fixtures = sorted(fixtures, key=lambda x: x["datetime"])[:5]
    
        return render_template("PremierLeague.html",  # change it if you want. dont bother
                        league_name=league_name,
                        league_code=league_code,
                        table=table,
                        recent_results=recent_results,
                        upcoming_fixtures=upcoming_fixtures)
# if anything leaking around:
@main.route('/PremierLeague')
def premier_league_redirect():
    return redirect(url_for('main.league_view', league_code="epl"))




@main.route('/createLeague', methods=["GET", "POST"])
def create_league():
    if "username" not in session:
        flash("You must be logged in to create a league")
        return redirect(url_for("main.login"))

    if request.method == "POST":
        league_name = request.form.get("league_name")
        league_type = request.form.get("league_type")
        privacy = request.form.get("privacy")
        username = session["username"]

        if not league_name or not league_type or not privacy:
            flash("All fields are required")
            return redirect(url_for("main.create_league"))

        success = add_fantasy_league(league_name, league_type, privacy, username)

        if success:
            if privacy == "Private":
                flash(f"League '{league_name}' created successfully! Your private code: {success}")
            else:
                flash(f"League '{league_name}' created successfully")
        else:
            flash("Error creating league. Please try again.", "danger")

        return redirect(url_for("main.create_league"))

    return render_template("createLeague.html")


@main.route("/joinLeague", methods=["GET", "POST"])
def join_league():
    if "username" not in session:
        flash("You must be logged in to join a league")
        return redirect(url_for("main.login"))

    username = session["username"]

    if request.method == "POST":
        league_code = request.form.get("league_code")
        league = get_league_by_code(league_code)

        if league:
            league_id = league["id"]

            if is_user_in_league(username, league_id):
                flash("You are already a member of this league")
            else:
                if add_user_to_league(username, league_id):
                    flash(f"Successfully joined private league: {league['league_name']}", "success")
                else:
                    flash("Error joining league. Try again")
        else:
            flash("Invalid league code")

        return redirect(url_for("main.join_league"))

    public_leagues = get_public_leagues()
    user_leagues_list = get_user_leagues(username)
    user_league_ids = [str(league['id']) for league in user_leagues_list]

    return render_template("joinLeague.html", leagues=public_leagues, user_leagues=user_league_ids)


#called when user presses the join button on public league
@main.route("/joinPublicLeague/<int:league_id>", methods=["POST"])
def join_public_league(league_id):
    if "username" not in session:
        flash("You must be logged in to join a league")
        return redirect(url_for("main.login"))

    username = session["username"]
    league = get_league_by_id(league_id)

    if league:
        if is_user_in_league(username, league_id):
            flash("You are already a member of this league")
        else:
            if add_user_to_league(username, league_id):
                flash(f"Successfully joined league: {league['league_name']}")
            else:
                flash("Error joining league")
    else:
        flash("League not found")

    return redirect(url_for("main.join_league"))



#called when user clicks on league name
@main.route("/league/<int:league_id>")
async def league(league_id):
    league = get_league_by_id(league_id)
    if not league:
        flash("League not found")
        return redirect(url_for("main.join_league"))

    league_type = league.get("league_type")
    members_str = league.get("members", "")
    member_list = [x.strip() for x in members_str.split(",") if x.strip()] if members_str else []
    league["member_list"] = member_list

    if league_type == "classic":
        league["leaderboard"] = get_league_leaderboard(league_id)
    elif league_type == "seasonal":
        league["leaderboard"] = get_seasonal_league_leaderboard(league_id)

        if league.get("season_end"):
            season_end_str = league["season_end"]
            try:
                season_end_dt = datetime.strptime(season_end_str, "%Y-%m-%d %H:%M:%S")
            except ValueError:
                season_end_dt = None

            if season_end_dt:
                diff = season_end_dt - datetime.now()
                time_left = int(diff.total_seconds())
                if time_left < 0:
                    time_left = 0
                league["time_left"] = time_left
            else:
                league["time_left"] = 0
        else:
            league["time_left"] = 0

    else:
        flash("error creating league leaderboard")
    
    recent_bets = []
    if league_type == "classic":
        recent_bets_info = get_recent_league_bets(league_id)
        
        # Get match details for these bets
        match_details = {}
        async with aiohttp.ClientSession() as session:
            understat = Understat(session)
            fixtures = await understat.get_league_fixtures("epl", 2024)
            results = await understat.get_league_results("epl", 2024)
            
            all_matches = fixtures + results
            
            # Get fixture IDs ezier
            fixture_ids = [f["id"] for f in fixtures]
            
            for match in all_matches:
                match_id = match["id"]
                match_details[match_id] = match
            
        # Combine bet info with match details
        for bet in recent_bets_info:
            match_id = bet['match_id']
            if match_id in match_details:
                match = match_details[match_id]
                # match still a fixture
                if match_id in fixture_ids:
                    bet['match'] = match
                    recent_bets.append(bet)

    return render_template("league.html", league=league, recent_bets=recent_bets)

@main.route('/place_bet', methods=['POST'])
def place_bet_route():
    if "username" not in session:

app/templates/PremierLeague.html
{% extends "base.html" %}

{% block main_content %}
<div class="league-view">
<div class="grid-container">
    <main>
        <h1>{{ league_name }} Table</h1>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Pos</th>
                        <th>Team</th>
                        <th>MP</th>
                        <th>W</th>
                        <th>D</th>
                        <th>L</th>
                        <th>GF</th>
                        <th>GA</th>
                        <th>GD</th>
                        <th>Pts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in table %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>
                          <img src="" class="team-crest" data-team="{{ row[0] }}">
                          <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=row[0]) }}" class="team-link">
                              {{ row[0] }}
                          </a>
                        </td>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[2] }}</td>
                        <td>{{ row[3] }}</td>
                        <td>{{ row[4] }}</td>
                        <td>{{ row[5] }}</td>
                        <td>{{ row[6] }}</td>
                        <td>{{ row[5]|int - row[6]|int }}</td>
                        <td>{{ row[7] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h2 class="section-title">Recent Results</h2>
        <div class="fixtures-container">
            {% for result in recent_results %}
            <a href="{{ url_for('main.single_result', league_code=league_code, match_id=result.id) }}" class="match-time-link">
              <div class="match-date">
                {{ result.datetime.split(' ')[0] }}
              </div>
            </a>
                <div class="match-teams">
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=result.h.title) }}" class="team-link">
                    <img src="" class="team-crest" data-team="{{ result.h.title }}">
                    <span class="team-name">{{ result.h.title }}</span>
                  </a>
                    <span class="score">{{ result.goals.h }} - {{ result.goals.a }}</span>
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=result.a.title) }}" class="team-link">
                    <span class="team-name">{{ result.a.title }}</span>
                    <img src="" class="team-crest" data-team="{{ result.a.title }}">
                  </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="section-title">Upcoming Fixtures</h2>
        <div class="fixtures-container">
            {% for fixture in upcoming_fixtures %}
            <a href="{{ url_for('main.prediction', league_code=league_code, match_id=fixture.id) }}" class="match-time-link">
              <div class="match-date">
                {{ fixture.datetime.split(' ')[0] }}
                <span class="match-time">{{ fixture.datetime.split(' ')[1][:5] }}</span>
              </div>
            </a>
                <div class="match-teams">
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=fixture.h.title)}}" class="team-link">
                    <img src="" class="team-crest" data-team="{{ fixture.h.title }}">
                      <span class="team-name">{{ fixture.h.title }}</span>
                  </a>
                    <span class="score">vs</span>
                  <a href="{{url_for('main.fixtures', league_code=league_code, team_name=fixture.a.title) }}" class="team-link">
                    <span class="team-name">{{ fixture.a.title }}</span>
                    <img src="" class="team-crest" data-team="{{ fixture.a.title }}">
                  </a>
                </div>
            {% endfor %}
        </div>
    </main>
    <footer>Footer</footer>
</div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Scoracle</title>
        <link rel="stylesheet" href="{{ url_for('static', filename = 'styles.css') }}">
        <script src="{{ url_for('static', filename = 'assignment.js') }}"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    </head>
    <body>
        <div class="animated-bg"></div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <ul class="Navbar">
            <li class="Scoracle-Logo">
                <a href="{{ url_for('main.homepage') }}"><img src="{{ url_for('static', filename='scoracle.png') }}" alt="scoracle logo"></a>
            </li>
            <li class="dropdown">
                <a href="{{ url_for('main.yourBets') }}" class="dropdown-trigger">yourBets</a>
            </li>
            <li class="dropdown">
                <a href="" class="dropdown-trigger">Fantasy Leagues</a>
                <div class="Content">
                    <a href="{{ url_for('main.create_league') }}">Create League</a>
                    <a href="{{ url_for('main.join_league') }}">Join League</a>
                    <a href="{{ url_for('main.my_leagues') }}">My Leagues</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-trigger">
                    <img src="{{ url_for('static', filename='PremLogo.png') }}" alt="Leagues Logo" class="nav-logo">
                    Leagues
                </a>
                <div class="Content">
                    <a href="{{ url_for('main.league_view', league_code='epl') }}">Premier League</a>
                    <a href="{{ url_for('main.league_view', league_code='La_liga') }}">La Liga</a>
                    <a href="{{ url_for('main.league_view', league_code='Bundesliga') }}">Bundesliga</a>
                    <a href="{{ url_for('main.league_view', league_code='Serie_A') }}">Serie A</a>
                    <a href="{{ url_for('main.league_view', league_code='Ligue_1') }}">Ligue 1</a>
                </div>
            </li>
            {% if session.username %}
                <li class="dropdown">
                    <a href="{{ url_for('main.home') }}">Hello, {{ session.username }}</a>
                </li>
                <li class="dropdown">
                    <a href="{{ url_for('main.logout') }}" class="dropdown-trigger">Logout</a>
                </li>
            {% else %}
            <li class="dropdown">
                <a href="{{ url_for('main.login') }}" class="dropdown-trigger">
                    <img src="{{ url_for('static', filename='login.png') }}" alt="Login Logo" class="nav-logo">
                    Login</a>
            </li>
            <li class="dropdown">
                <a href="{{ url_for('main.register') }}" class="dropdown-trigger">
                    <img src="{{ url_for('static', filename='registerLogo.webp') }}" alt="Premier League Logo" class="nav-logo">
                    Register</a>
            </li>
            {% endif %}
        </ul>
        <br>
        <br>
        <br>
        <br>
        <br>
        {% block main_content %}
        {% endblock %}
    </body>
</html>

app/templates/createLeague.html
{% extends "base.html" %}

{% block main_content %}
<div class="create-league">
<div class="grid-container">
    <main>
        <form method="POST" action="{{ url_for('main.create_league') }}">
          <label>League Name</label>
          <input type="text" class="leagueName" name="league_name" id="leagueName" required>

          <label>Type of League</label>
          <select name="league_type" id="leagueType" required>
            <option value="classic">Classic</option>
            <option value="seasonal">Seasonal</option>
          </select>

          <label>Privacy</label>
          <select name="privacy" id="privacy" required>
            <option value="Public">Public League</option>
            <option value="Private">Private League</option>
          </select>
          <br></br>
          <button class="createSubmit" type="submit">Create League</button>
        </form>

    </main>
    </div>
</div>
{% endblock %}

app/templates/currentLeagues.html
{% extends "base.html" %}

{% block main_content %}
<div class="grid-container">
 
    <main>
        <p>Main articles go here need to be figured later</p>
    </main>

      <footer>Footer</footer>
    </div>
{% endblock %}

app/templates/fixtures.html
{% extends "base.html" %}

{% block main_content %}
<div class="fixtures">
<div class="grid-container">
  <main>
    {% if team_name %}
        <h1>{{ team_name }} Fixtures and Results</h1>
        
        <!-- Recent Results Section -->
        <h2 class="section-title">Recent Results</h2>
        <div class="fixtures-container">
            {% for result in recent_results %}
            <a href="{{ url_for('main.single_result', match_id=result.id) }}" class="match-time-link">
                <div class="match-date">
                  {{ result.datetime.split(' ')[0] }}
                </div>
              </a>
                <div class="match-teams">
                    <a href="{{ url_for('main.fixtures', team_name=result.h.title) }}" class="team-link">
                        <img src="" class="team-crest" data-team="{{ result.h.title }}">
                        <span class="team-name {% if result.h.title == team_name %}highlighted-team{% endif %}">
                            {{ result.h.title }}
                        </span>
                    </a>
                    <span class="score">{{ result.goals.h }} - {{ result.goals.a }}</span>
                    <a href="{{ url_for('main.fixtures', team_name=result.a.title) }}" class="team-link">
                        <span class="team-name {% if result.a.title == team_name %}highlighted-team{% endif %}">
                            {{ result.a.title }}
                    </span>
                    <img src="" class="team-crest" data-team="{{ result.a.title }}">
                    </a>
                </div>

            {% endfor %}
        </div>

        <!-- Upcoming Fixtures Section whatever added to prem table can be added to here cos they're practically same thing... if you want to keep it like that-->
        <h2 class="section-title">Upcoming Fixtures</h2>
        <div class="fixtures-container">
            {% for fixture in upcoming_fixtures %}
            <a href="{{ url_for('main.prediction', match_id=fixture.id) }}" class="match-time-link">  
              <div class="match-date">
                {{ fixture.datetime.split(' ')[0] }}
                <span class="match-time">{{ fixture.datetime.split(' ')[1][:5] }}</span>
              </div>
            </a>
                <div class="match-teams">
                    <a href="{{ url_for('main.fixtures', team_name=fixture.h.title) }}" class="team-link">
                        <img src="" class="team-crest" data-team="{{ fixture.h.title }}">
                        <span class="team-name {% if fixture.h.title == team_name %}highlighted-team{% endif %}">
                            {{ fixture.h.title }}
                        </span>
                    </a>
                    <span class="score">vs</span>
                    <a href="{{ url_for('main.fixtures', team_name=fixture.a.title) }}" class="team-link">
                        <span class="team-name {% if fixture.a.title == team_name %}highlighted-team{% endif %}">
                            {{ fixture.a.title }}
                        </span>
                        <img src="" class="team-crest" data-team="{{ fixture.a.title }}">
                    </a>
                </div>


            {% endfor %}
        </div>
    {% else %}
        <h1>Premier League Fixtures</h1>
        <p>Select a team from the Premier League table to view their fixtures and results.</p>
    {% endif %}
</main>

      <footer>Footer</footer>
</div>
</div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block main_content %}
    <div class="grid-container">
      <main class="dashboard">
        <h1>Welcome to Scoracle, {{ username }}</h1>
        <div class="dash-head">
            <p>You are in {{ leagues }} Leagues! View them <a href="{{ url_for('main.my_leagues') }}">here</a>!</p>
            {% if profile_pic %}
              <img class="profile-pic" src={{profile_pic}} alt="Profile picture">
            {% else %}
              <img class="profile-pic" src="{{ url_for('static', filename='login.png') }}" alt="Profile picture">
            {% endif %}
            <p>Look for leagues <a href="{{ url_for('main.join_league') }}">here</a>!</p>
            <p>Create a league <a href="{{ url_for('main.create_league') }}">here</a>!</p>
        </div> 
        <a class="logout" href="{{ url_for('main.logout') }}">Logout</a>


        <div class="Update">
          <h1>Update</h1>
          <form class="Update" method="POST" enctype="multipart/form-data">
            <p>
              {{ form.hidden_tag() }}
              {{ form.username.label }} 
              {{ form.username() }}
              {% for error in form.username.errors %}
                  {{ error }}
              {% endfor %}
            </p>
            <br>
            <p>
              {{ form.favourite_team.label }}
              {{ form.favourite_team() }}
            </p>
            <br>
            <p>
              {{ form.profile_pic.label }}
              {{ form.profile_pic() }}
              {% for error in form.profile_pic.errors %}
                  {{ error }}
              {% endfor %}
            </p>
            <br>
            <p>
              {{ form.update() }}
            </p>
          </form>
        </div>
      </main>
      <footer>Footer</footer>
    </div>

{% endblock %}

app/templates/joinLeague.html
{% extends "base.html" %}

{% block main_content %}
<div class="join-league">
  <div class="grid-container">
    <main class="league-container">
      
      <div class="join-form">
        <h2>Join A Private League</h2>
        <form method="POST" action="{{ url_for('main.join_league') }}">
          <input type="text" name="league_code" required placeholder="Enter Code...">
          <button type="submit" class="private-join">Join</button>
        </form>
      </div>

    <div class="public-leagues">
      <h1>Public Leagues</h1>
      {% if leagues %}
        <table class="league-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Created</th>
              <th>Members</th>
              <th>Creator</th>
              <th> </th>
            </tr>
          </thead>
          <tbody>
            {% for league in leagues %}
              <tr>
                <td><a href="{{ url_for('main.league', league_id=league.id) }}">{{ league.name }}</a></td>
                <td>{{ league.league_type|capitalize }}</td>
                <td>{{ league.created_at.split(' ')[0] }}</td>
                <td>{{ league.members.split(',')|length }}</td>
                <td>{{ league.creator }}</td>
                <td>
                  {% if league.id|string not in user_leagues %}
                    <form action="{{ url_for('main.join_public_league', league_id=league.id) }}" method="POST">
                      <button type="submit" class="btn-join">JOIN</button>
                    </form>
                  {% else %}
                    <button disabled class="btn-disabled">Joined</button>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p class="no-leagues">No public leagues available.</p>
      {% endif %}
    </div>
  </main>
  </div>
</div>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block main_content %}
<div class="grid-container">
    <main>
      <div class="intro">
          <img src="{{ url_for('static', filename='scoracle.png') }}" alt="scoracle logo"/>
          <h1>Scoracle</h1>
          <p>Welcome to Scoracle! Register and start your own Fantasy Football League, combining analysis with competition through informed statistics!</p>
          <br>
          <p>Join a league, create your own or browse our insightful statistics!</p>
          <br>
      </div>
    <h2 class="section-title">Recent Results</h2>
        <div class="fixtures-container">
            {% for result in recent_results %}
            <a href="{{ url_for('main.single_result', league_code=league_code, match_id=result.id) }}" class="match-time-link">
              <div class="match-date">
                {{ result.datetime.split(' ')[0] }}
              </div>
            </a>
                <div class="match-teams">
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=result.h.title) }}" class="team-link">
                    <img src="" class="team-crest" data-team="{{ result.h.title }}">
                    <span class="team-name">{{ result.h.title }}</span>
                  </a>
                    <span class="score">{{ result.goals.h }} - {{ result.goals.a }}</span>
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=result.a.title) }}" class="team-link">
                    <span class="team-name">{{ result.a.title }}</span>
                    <img src="" class="team-crest" data-team="{{ result.a.title }}">
                  </a>
                </div>
            {% endfor %}
        </div>

        <h2 class="section-title">Upcoming Fixtures</h2>
        <div class="fixtures-container">
            {% for fixture in upcoming_fixtures %}
            <a href="{{ url_for('main.prediction', league_code=league_code, match_id=fixture.id) }}" class="match-time-link">
              <div class="match-date">
                {{ fixture.datetime.split(' ')[0] }}
                <span class="match-time">{{ fixture.datetime.split(' ')[1][:5] }}</span>
              </div>
            </a>
                <div class="match-teams">
                  <a href="{{ url_for('main.fixtures', league_code=league_code, team_name=fixture.h.title)}}" class="team-link">
                    <img src="" class="team-crest" data-team="{{ fixture.h.title }}">
                      <span class="team-name">{{ fixture.h.title }}</span>
                  </a>
                    <span class="score">vs</span>
                  <a href="{{url_for('main.fixtures', league_code=league_code, team_name=fixture.a.title) }}" class="team-link">
                    <span class="team-name">{{ fixture.a.title }}</span>
                    <img src="" class="team-crest" data-team="{{ fixture.a.title }}">
                  </a>
                </div>
            {% endfor %}
        </div>
    </main>
</div>


{% endblock %}

app/templates/myLeagues.html
{% extends "base.html" %}

{% block main_content %}
<div class="join-league">
    <div class="grid-container">
        <main class="leagues-container">
            <h1>My Leagues</h1>

            {% if leagues %}
            <div class="public-leagues">
                <table class="league-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>created</th>
                            <th>members</th>
                            <th>Creator</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for league in leagues %}
                            <tr onclick="window.location.href='{{ url_for('main.league', league_id=league.id) }}'">
                                <td>{{ league.name }}</td>
                                <td>{{ league.league_type|capitalize }}</td>
                                <td>{{ league.created_at.split(' ')[0] }}</td>
                                <td>{{ league.members.split(',')|length }}</td>
                                <td>{{ league.creator }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            <div class="public-leagues">
            {% else %}
                <p class="no-leagues">You are not in any leagues yet.</p>
            {% endif %}
        </main>
    </div>
</div>
{% endblock %}

app/templates/results.html
{% extends "base.html" %}

{% block main_content %}
<div class="grid-container">
 
    <main>
        <h2>Search Results</h2>
        <p>You searched for <b>{{ query }}</b></p>
        {% if results %}
        <ul>
            {%for item in results %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No results found </p>
        {% endif %}
    </main>
      <footer>Footer</footer>
    </div>
{% endblock %} 